MODEL (
  enabled TRUE,
  kind VIEW,
  tags uss
);

SELECT
  *
FROM gold._bridge__as_is
LEFT JOIN gold.persons USING (_pit_hook__person__individual)
LEFT JOIN gold.customers USING (_pit_hook__customer)
LEFT JOIN gold.employees USING (_pit_hook__person__employee)
LEFT JOIN gold.products USING (_pit_hook__product)
LEFT JOIN gold.sales_order_headers USING (_pit_hook__order__sales)
LEFT JOIN gold.sales_order_details USING (_pit_hook__order_line__sales)
LEFT JOIN gold.sales_territories USING (_pit_hook__territory__sales)
LEFT JOIN gold.addresses USING (_pit_hook__address)
LEFT JOIN gold.departments USING (_pit_hook__department)
LEFT JOIN gold.vendors USING (_pit_hook__vendor)
LEFT JOIN gold.stores USING (_pit_hook__store)
LEFT JOIN gold.sales_persons USING (_pit_hook__person__sales)
LEFT JOIN gold.credit_cards USING (_pit_hook__credit_card)
LEFT JOIN gold.ship_methods USING (_pit_hook__ship_method)
LEFT JOIN gold.product_categories USING (_pit_hook__product_category)
LEFT JOIN gold.product_subcategories USING (_pit_hook__product_subcategory)
LEFT JOIN gold.currencies USING (_pit_hook__currency)
LEFT JOIN gold.work_orders USING (_pit_hook__order__work)
LEFT JOIN gold.currency_rates USING (_pit_hook__currency_rate)
LEFT JOIN gold.employee_pay_histories USING (_pit_hook__person__employee)
LEFT JOIN gold.employee_department_histories USING (_pit_hook__person__employee)
LEFT JOIN gold.job_candidates USING (_pit_hook__job_candidate)
LEFT JOIN gold.shifts USING (_pit_hook__reference__shift)
LEFT JOIN gold.address_types USING (_pit_hook__reference__address_type)
LEFT JOIN gold.business_entity_addresses USING (_pit_hook__address)
LEFT JOIN gold.business_entity_contacts USING (_pit_hook__business_entity)
LEFT JOIN gold.contact_types USING (_pit_hook__reference__contact_type)
LEFT JOIN gold.country_regions USING (_pit_hook__reference__country_region)
LEFT JOIN gold.email_addresses USING (_pit_hook__person__individual)
LEFT JOIN gold.person_phones USING (_pit_hook__person__individual)
LEFT JOIN gold.phone_number_types USING (_pit_hook__reference__phone_number_type)
LEFT JOIN gold.bill_of_materials USING (_pit_hook__bill_of_materials)
LEFT JOIN gold.cultures USING (_pit_hook__reference__culture)
LEFT JOIN gold.illustrations USING (_pit_hook__reference__illustration)
LEFT JOIN gold.locations USING (_pit_hook__reference__location)
LEFT JOIN gold.product_cost_histories USING (_pit_hook__product)
LEFT JOIN gold.product_descriptions USING (_pit_hook__reference__product_description)
LEFT JOIN gold.product_inventories USING (_pit_hook__reference__location)
LEFT JOIN gold.product_list_price_histories USING (_pit_hook__product)
LEFT JOIN gold.product_model_illustrations USING (_pit_hook__reference__illustration)
LEFT JOIN gold.product_models USING (_pit_hook__reference__product_model)
LEFT JOIN gold.product_photos USING (_pit_hook__reference__product_photo)
LEFT JOIN gold.product_reviews USING (_pit_hook__product_review)
LEFT JOIN gold.scrap_reasons USING (_pit_hook__reference__scrap_reason)
LEFT JOIN gold.transaction_histories USING (_pit_hook__transaction_history)
LEFT JOIN gold.transaction_history_archives USING (_pit_hook__transaction_history_archive)
LEFT JOIN gold.unit_measures USING (_pit_hook__reference__unit_measure)
LEFT JOIN gold.work_order_routings USING (_pit_hook__order_line__work)
LEFT JOIN gold.product_vendors USING (_pit_hook__vendor)
LEFT JOIN gold.purchase_order_headers USING (_pit_hook__order__purchase)
LEFT JOIN gold.purchase_order_details USING (_pit_hook__order_line__purchase)
LEFT JOIN gold.special_offers USING (_pit_hook__reference__special_offer)
LEFT JOIN gold.shopping_cart_items USING (_pit_hook__shopping_cart_item)
LEFT JOIN gold.sales_territory_histories USING (_pit_hook__person__sales)
LEFT JOIN gold.sales_tax_rates USING (_pit_hook__reference__sales_tax_rate)
LEFT JOIN gold.state_provinces USING (_pit_hook__reference__state_province)
LEFT JOIN gold.sales_person_quota_histories USING (_pit_hook__person__sales)
LEFT JOIN gold.sales_reasons USING (_pit_hook__reference__sales_reason)